// <auto-generated />
using CadastroCliente.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroClientes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250331030455_PopulaTabelaTest")]
    partial class PopulaTabelaTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroCliente.Models.ClienteTest", b =>
                {
                    b.Property<int>("ColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColaboradorId"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContatoResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Funcao")
                        .HasColumnType("int");

                    b.Property<string>("FuncoesTerceirizadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Posto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColaboradorId");

                    b.ToTable("ClienteTest");

                    b.HasData(
                        new
                        {
                            ColaboradorId = 1,
                            Bairro = "Miramar",
                            ContatoResponsavel = "83981295876",
                            Endereco = "RUA DOMINGOS MOROSO, S/N MIRAMAR EM JOAO PESSOA NO ESTADO DA PB, CEP:58043-170",
                            Funcao = 1,
                            FuncoesTerceirizadas = "NPS",
                            NomeResponsavel = "Antônio Henrique",
                            Posto = "Arvoredo"
                        },
                        new
                        {
                            ColaboradorId = 2,
                            Bairro = "Bessa",
                            ContatoResponsavel = "83981295876",
                            Endereco = "AVENIDA PRESIDENTE AFONSO PENA, 382, BESSA, EM JOAO PESSOA NO ESTADO DA PB, CEP: 58035-030",
                            Funcao = 0,
                            FuncoesTerceirizadas = "NPS",
                            NomeResponsavel = "Mariana",
                            Posto = "Imperial Bessa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
