// <auto-generated />
using CadastroCliente.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroClientes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401143138_populaTabela")]
    partial class populaTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroCliente.Models.ClienteTest", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ClienteBairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteContato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteFuncaoResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("ClienteFuncoesTerceirizadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientePosto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteResponsavel")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ClienteId");

                    b.ToTable("ClienteTest");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            ClienteBairro = "Miramar",
                            ClienteContato = "83981295876",
                            ClienteEndereco = "RUA DOMINGOS MOROSO, S/N MIRAMAR EM JOAO PESSOA NO ESTADO DA PB, CEP:58043-170",
                            ClienteFuncaoResponsavel = 1,
                            ClienteFuncoesTerceirizadas = "NPS",
                            ClientePosto = "Arvoredo",
                            ClienteResponsavel = "Antônio Henrique"
                        },
                        new
                        {
                            ClienteId = 2,
                            ClienteBairro = "Bessa",
                            ClienteContato = "83981295876",
                            ClienteEndereco = "AVENIDA PRESIDENTE AFONSO PENA, 382, BESSA, EM JOAO PESSOA NO ESTADO DA PB, CEP: 58035-030",
                            ClienteFuncaoResponsavel = 0,
                            ClienteFuncoesTerceirizadas = "NPS",
                            ClientePosto = "Imperial Bessa",
                            ClienteResponsavel = "Mariana"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
