// <auto-generated />
using System;
using CadastroCliente.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadastroClientes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515212111_FormularioOperacional")]
    partial class FormularioOperacional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadastroCliente.Models.ClienteTest", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ClienteBairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientebairro");

                    b.Property<string>("ClienteContato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientecontato");

                    b.Property<string>("ClienteEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteendereco");

                    b.Property<int>("ClienteFuncaoResponsavel")
                        .HasColumnType("integer")
                        .HasColumnName("clientefuncaoresponsavel");

                    b.Property<string>("ClienteFuncoesTerceirizadas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientefuncoesterceirizadas");

                    b.Property<string>("ClientePosto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteposto");

                    b.Property<string>("ClienteResponsavel")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("clienteresponsavel");

                    b.HasKey("ClienteId");

                    b.ToTable("clientetest");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            ClienteBairro = "Miramar",
                            ClienteContato = "83981295876",
                            ClienteEndereco = "RUA DOMINGOS MOROSO, S/N MIRAMAR EM JOAO PESSOA NO ESTADO DA PB, CEP:58043-170",
                            ClienteFuncaoResponsavel = 1,
                            ClienteFuncoesTerceirizadas = "NPS",
                            ClientePosto = "Arvoredo",
                            ClienteResponsavel = "Antônio Henrique"
                        },
                        new
                        {
                            ClienteId = 2,
                            ClienteBairro = "Bessa",
                            ClienteContato = "83981295876",
                            ClienteEndereco = "AVENIDA PRESIDENTE AFONSO PENA, 382, BESSA, EM JOAO PESSOA NO ESTADO DA PB, CEP: 58035-030",
                            ClienteFuncaoResponsavel = 0,
                            ClienteFuncoesTerceirizadas = "NPS",
                            ClientePosto = "Imperial Bessa",
                            ClienteResponsavel = "Mariana"
                        });
                });

            modelBuilder.Entity("CadastroClientes.Models.FormularioOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("formularioid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoIgo")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaoigo");

                    b.Property<int>("AvaliacaoRobson")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaorobson");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("clienteposto");

                    b.Property<int>("ClientePostoClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientesAtendidos")
                        .HasColumnType("integer")
                        .HasColumnName("clientesatendidos");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataenvio");

                    b.Property<int>("GestoresAtendidos")
                        .HasColumnType("integer")
                        .HasColumnName("gestoresatendidos");

                    b.Property<DateTime>("HoraEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horaenvio");

                    b.Property<string>("ObservacoesGerais")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observacoesgerais");

                    b.Property<string>("ProblemasIdentificados")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("problemasidentificados");

                    b.Property<int>("ProblemasReportados")
                        .HasColumnType("integer")
                        .HasColumnName("problemasreportados");

                    b.Property<string>("SolucoesApresentadas")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("solucoesapresentadas");

                    b.HasKey("Id");

                    b.HasIndex("ClientePostoClienteId");

                    b.ToTable("formulariooperacional");
                });

            modelBuilder.Entity("CadastroClientes.Models.FormularioOperacional", b =>
                {
                    b.HasOne("CadastroCliente.Models.ClienteTest", "ClientePosto")
                        .WithMany()
                        .HasForeignKey("ClientePostoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientePosto");
                });
#pragma warning restore 612, 618
        }
    }
}
