// <auto-generated />
using System;
using CadastroCliente.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadastroClientes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118022300_formularioSupervisao")]
    partial class formularioSupervisao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadastroCliente.Models.ClientesHumanas", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ClienteBairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientebairro");

                    b.Property<string>("ClienteContato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientecontato");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteemail");

                    b.Property<string>("ClienteEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteendereco");

                    b.Property<string>("ClienteFuncaoResponsavel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientefuncaoresponsavel");

                    b.Property<string>("ClienteObservacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteobservacao");

                    b.Property<string>("ClientePosto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteposto");

                    b.Property<string>("ClienteResponsavel")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("clienteresponsavel");

                    b.HasKey("ClienteId");

                    b.ToTable("clienteshumanas");
                });

            modelBuilder.Entity("CadastroCliente.Models.LeadsOperacionais", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("leadid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadId"));

                    b.Property<string>("LeadEmail")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("leademail");

                    b.Property<string>("LeadName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("leadname");

                    b.Property<string>("LeadPassword")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("leadpassword");

                    b.Property<int>("LeadRole")
                        .HasColumnType("integer")
                        .HasColumnName("leadcreateddate");

                    b.HasKey("LeadId");

                    b.ToTable("LeadsOperacionais");
                });

            modelBuilder.Entity("CadastroClientes.Models.FormularioOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("formularioid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoIgo")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaoigo");

                    b.Property<int>("AvaliacaoRobson")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaorobson");

                    b.Property<string>("ClientePosto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteposto");

                    b.Property<int>("ClientesAtendidos")
                        .HasColumnType("integer")
                        .HasColumnName("clientesatendidos");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataenvio");

                    b.Property<int>("GestoresAtendidos")
                        .HasColumnType("integer")
                        .HasColumnName("gestoresatendidos");

                    b.Property<DateTime>("HoraEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horaenvio");

                    b.Property<string>("ObservacoesGerais")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("observacoesgerais");

                    b.Property<string>("ProblemasIdentificados")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("problemasidentificados");

                    b.Property<int>("ProblemasReportados")
                        .HasColumnType("integer")
                        .HasColumnName("problemasreportados");

                    b.Property<string>("SolucoesApresentadas")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("solucoesapresentadas");

                    b.HasKey("Id");

                    b.ToTable("formulariooperacional");
                });

            modelBuilder.Entity("CadastroClientes.Models.Ocorrencias", b =>
                {
                    b.Property<int>("OcorrenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ocorrenciaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OcorrenciaId"));

                    b.Property<string>("ClientePosto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteposto");

                    b.Property<string>("ClienteResponsavel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteresponsavel");

                    b.Property<DateTime>("OcorrenciaData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrenciadata");

                    b.Property<string>("OcorrenciaDescricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocorrenciadescricao");

                    b.Property<int>("OcorrenciaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("ocorrenciastatus");

                    b.HasKey("OcorrenciaId");

                    b.ToTable("ocorrencias");
                });

            modelBuilder.Entity("CadastroClientes.Models.Reclamacoes", b =>
                {
                    b.Property<int>("Reclamacaoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reclamacaoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Reclamacaoid"));

                    b.Property<string>("ClientePosto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clienteposto");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReclamacaoData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reclamacaodata");

                    b.Property<string>("ReclamacaoDescricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reclamacaodescricao");

                    b.Property<string>("ReclamacaoResolucao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reclamacaoresolucao");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Reclamacaoid");

                    b.ToTable("reclamacoes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
